In [1]:
# Define scalars
a = 5
b = 3

# Addition
addition = a + b
print(f"{a} + {b} = {addition}")

# Subtraction
subtraction = a - b
print(f"{a} - {b} = {subtraction}")

# Multiplication
multiplication = a * b
print(f"{a} * {b} = {multiplication}")

# Division
division = a / b
print(f"{a} / {b} = {division}")

# Power
power = a ** b
print(f"{a} ^ {b} = {power}")

# Modulus
modulus = a % b
print(f"{a} % {b} = {modulus}")


5 + 3 = 8
5 - 3 = 2
5 * 3 = 15
5 / 3 = 1.6666666666666667
5 ^ 3 = 125
5 % 3 = 2


In [3]:
import numpy as np

# Define vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Print the vectors
print("Vector A:", vector_a)
print("Vector B:", vector_b)

# Vector addition
vector_add = vector_a + vector_b
print("Addition:", vector_add)

# Vector subtraction
vector_subtract = vector_a - vector_b
print("Subtraction:", vector_subtract)

# Dot product
dot_product = np.dot(vector_a, vector_b)
print("Dot Product:", dot_product)

# Cross product (only for 3D vectors)
cross_product = np.cross(vector_a, vector_b)
print("Cross Product:", cross_product)

# Magnitude (norm) of a vector
magnitude_a = np.linalg.norm(vector_a)
magnitude_b = np.linalg.norm(vector_b)
print("Magnitude of Vector A:", magnitude_a)
print("Magnitude of Vector B:", magnitude_b)

# Angle between two vectors
cos_angle = dot_product / (magnitude_a * magnitude_b)
angle = np.arccos(cos_angle)
print("Angle between vectors (in radians):", angle)
print("Angle between vectors (in degrees):", np.degrees(angle))


Vector A: [1 2 3]
Vector B: [4 5 6]
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Dot Product: 32
Cross Product: [-3  6 -3]
Magnitude of Vector A: 3.7416573867739413
Magnitude of Vector B: 8.774964387392123
Angle between vectors (in radians): 0.2257261285527342
Angle between vectors (in degrees): 12.933154491899135


In [5]:
import numpy as np

# Create matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Matrix addition
C = A + B
print("Matrix Addition:\n", C)

# Matrix subtraction
D = A - B
print("Matrix Subtraction:\n", D)

# Matrix multiplication (element-wise)
E = A * B
print("Element-wise Multiplication:\n", E)

# Matrix multiplication (dot product)
F = np.dot(A, B)
print("Dot Product:\n", F)

# Matrix transpose
G = A.T
print("Transpose of A:\n", G)

# Matrix inverse (only for square matrices)
# Using a smaller matrix for demonstration as A is singular (non-invertible)
H = np.array([[1, 2], [3, 4]])
H_inv = np.linalg.inv(H)
print("Inverse of H:\n", H_inv)

# Matrix determinant
det_A = np.linalg.det(A)
print("Determinant of A:\n", det_A)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:\n", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)


Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Dot Product:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Inverse of H:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A:
 -9.51619735392994e-16
Eigenvalues of A:
 [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Eigenvectors of A:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [7]:
import numpy as np

# Creating tensors
tensor_a = np.array([[1, 2], [3, 4]])
tensor_b = np.array([[5, 6], [7, 8]])

print("Tensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)

# Basic tensor operations

# Addition
tensor_add = np.add(tensor_a, tensor_b)
print("\nAddition of A and B:\n", tensor_add)

# Subtraction
tensor_sub = np.subtract(tensor_a, tensor_b)
print("\nSubtraction of B from A:\n", tensor_sub)

# Element-wise multiplication
tensor_mul = np.multiply(tensor_a, tensor_b)
print("\nElement-wise multiplication of A and B:\n", tensor_mul)

# Matrix multiplication
tensor_dot = np.dot(tensor_a, tensor_b)
print("\nMatrix multiplication of A and B:\n", tensor_dot)

# Transposition
tensor_transpose = np.transpose(tensor_a)
print("\nTranspose of A:\n", tensor_transpose)

# Determinant
tensor_det = np.linalg.det(tensor_a)
print("\nDeterminant of A:\n", tensor_det)

# Inverse
tensor_inv = np.linalg.inv(tensor_a)
print("\nInverse of A:\n", tensor_inv)

# Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(tensor_a)
print("\nEigenvalues of A:\n", eigenvalues)
print("\nEigenvectors of A:\n", eigenvectors)


Tensor A:
 [[1 2]
 [3 4]]
Tensor B:
 [[5 6]
 [7 8]]

Addition of A and B:
 [[ 6  8]
 [10 12]]

Subtraction of B from A:
 [[-4 -4]
 [-4 -4]]

Element-wise multiplication of A and B:
 [[ 5 12]
 [21 32]]

Matrix multiplication of A and B:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Determinant of A:
 -2.0000000000000004

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues of A:
 [-0.37228132  5.37228132]

Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [9]:
import numpy as np

# Define a square matrix
A = np.array([[4, -2],
              [1, 1]])

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)


Matrix A:
[[ 4 -2]
 [ 1  1]]

Eigenvalues:
[3. 2.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [11]:
import numpy as np

# Define a vector
v = np.array([3, 4, -2])

# L1 norm
l1_norm = np.linalg.norm(v, 1)
print(f"L1 norm: {l1_norm}")

# L2 norm
l2_norm = np.linalg.norm(v)
print(f"L2 norm: {l2_norm}")

# Infinity norm
inf_norm = np.linalg.norm(v, np.inf)
print(f"Infinity norm: {inf_norm}")


L1 norm: 9.0
L2 norm: 5.385164807134504
Infinity norm: 4.0
